name: build-image-docker

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-image-docker:
    env:
      TAG: diegodamato/test-github-actions:${GITHUB_REF/refs\/tags\//}
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set version tag
        run: echo '::set-output name=VERSION_TAG::${GITHUB_REF/refs\/tags\//}'
        id: version-tag

      - name: Get version tag
        run: echo "The selected color is ${{ steps.version-tag.outputs.VERSION_TAG }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./../../
          file: ./Dockerfile
          push: true
          tags: diegodamato/test-github-actions:${{ steps.version-tag.outputs.VERSION_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
