name: build-image-docker

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-image-docker:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

       - name: Login to Docker Hub
          uses: docker/login-action@v1
          environment: 
            name: secrets
          with:
            username: ${{secrets.DOCKER_HUB_USERNAME}}
            password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      # - name: login docker Hub
      #   run: |
      #     docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./../../
          file: ./Dockerfile
          push: true
          tags: diegodamato/test-github-actions:latest

      - name: Image digest
        run: echo ${{steps.docker_build.outputs.digest}}
